### ISSUE TITLE
Different syntax?

### ISSUE THREAD

**Issue by dpc** [coastalwhite/rustlogic#1]
I'm looking for a create just like this one, but I'd like the user provide the expression. I was hoping for something more like `a AND b`, `foo OR (bar AND baz)` etc.

**Comment by coastalwhite** [comment]
Hey David, thanks for your issue.

This is something I thought about during development, and therefore it is implemented in the backend of the library. It is not available from the outside though. I'll have a look in the coming days, if I can find a way of opening this up.

It is important to note that then it would only work with infix notation. For prefix and suffix notation the parser would need some overhauling.

**Comment by dpc** [comment]
For me infix notation is the only one that matter, I guess. Usually in my programs I have some need to to expose to the user some filtering based on criteria: eg. find all things that match a given logical expression of attributes. And most users will be familiar with infix.

**Comment by coastalwhite** [comment]
Hello David,

This issue is now implemented in  **rustlogic 0.2.0**
Have a look at [the docs](https://docs.rs/rustlogic/0.2.0/rustlogic/operators/struct.OperatorSet.html) for plenty of examples on how to use it.

Hope this helps!

**Comment by dpc** [comment]
Wow! Thanks a lot!
