### ISSUE TITLE
Parsing panics on malformed query

### ISSUE THREAD

**Issue by Emily3403** [coastalwhite/rustlogic#3]
Hey there! First of all thank you for this great crate. It simplifies my parsing logic massively and I am very thankful for that.

Unfortunately, during my tests, I have discovered that the following malformed query will cause a panic instead of returning a `Result`: 
```rust
rustlogic::parse("][]")
```

This issue is caused by a bug in `src/util.rs:53`. The `pool` is indexed with `pool[1..]`, however it is not checked if the pool actually contains any elements, only if it contains exactly one element.

I have identified two possible solutions to this issue:

- Extending the existing code to
```rust
if pool.len() == 0 || pool.len() == 1 {
    return None;
}
```

- Modifying the existing code as follows
```rust
if pool.len() <= 1 {
    return None;
}
```

With the bounds correctly adjusted, the function does not panic anymore. 

In an optimized build both solutions should be equivalent in terms of assembly code generated, so feel free to choose whichever suits your style 😊

**Comment by Emily3403** [comment]
*bump*

**Comment by coastalwhite** [comment]
Oh! Wow! Sorry, completely missed this message in my GitHub. I have updated the package with a fix.

Thank you for reporting.
